### ISSUE TITLE
Integration with symfony

### ISSUE THREAD

**Issue by muspelheim** [biberlabs/ddd-embeddables#11]
Hello, I trying integrate this bundle with symfony, but it's not work for me.

``` php
/**
     * @ORM\Embedded(class="DDD\Embeddable\EmailAddress")
     */
    private $email;
```

This I add to my entity, after run command **bin/console doctrine:generate:entities** I get this result:

``` php
/**
     * Set email
     * @return Test
     */
    public function setEmail(EmailAddress $email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return EmailAddress
     */
    public function getEmail()
    {
        return $this->email;
    }
```

In this case we can't create simple object as:

``` php
$test = new Test();
$test->setEmail('test@ddd.dd');
```

Because method setEmail **must be an instance of EmailAddress, string given** and it's useless for development. In this case we can manually create method

``` php
public function setEmail($email)
    {
        $this->email = new EmailAddress($email);
        return $this;
    }
```

but this solution is very difficult to extend, may be you have solution for this case?

``` php
$prod->setColor(new Color('#FF00FF'));
```

this case is difficult for development.

**Comment by hkulekci** [comment]
In my opinion, you can use a trait for situations such this. After pairing the embeddable to owning entity, you can utilize a trait for setter and getters of value object. Right now, this repository have not any trait implementation, please don't hesitate to give opinion if there is any other solution or way to deal with. @muspelheim

**Comment by edigu** [comment]
@muspelheim thanks for your interest. Seems like your case is related with object hydration and imho there is nothing to do within this library except allowing empty values in constructors. After your comment I realized this detail and I will try to create another PR to convert all ctors args to optional.

Another detail is, reason behind existence of the `bin/console doctrine:generate:entities` command is helping developers to easily generate entities from an existing schema. The output of the command should not interpret as a "final" entity. We can (and must) always write additional methods to our entities when required and after that point `doctrine:generate:entities` lose it's meaning.

As you know there is no [method overloading](https://en.wikipedia.org/wiki/Function_overloading) in PHP, but if you don't want to create a custom hydrator for your `User`, having a setter like below completely valid:

```
public function setEmail($email)
{
    $this->email = ($email instanceof EmailAddress) ? $email : new EmailAddress($email);
    return $this;
}
```

Yes, it looks ugly and I also prefer to have type hinting here but don't know is there is a better approach exists or not.

**Comment by edigu** [comment]
All embeddables now supports empty state. Closing this. Hydration of domain entities should be handled in other application layers.
